config/routes.rb
Rails.application.routes.draw do

  resources :substates
  resources :constituencies
  resources :states do
    #resources :constituencies do
    #  resources :projects
    #end
  end

  root 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/substate.rb
class Substate < ApplicationRecord
end

app/controllers/substates_controller.rb
class SubstatesController < ApplicationController
  before_action :set_substate, only: [:show, :edit, :update, :destroy]

  # GET /substates
  # GET /substates.json
  def index
    @substates = Substate.all
  end

  # GET /substates/1
  # GET /substates/1.json
  def show
  end

  # GET /substates/new
  def new
    @substate = Substate.new
  end

  # GET /substates/1/edit
  def edit
  end

  # POST /substates
  # POST /substates.json
  def create
    @substate = Substate.new(substate_params)

    respond_to do |format|
      if @substate.save
        format.html { redirect_to @substate, notice: 'Substate was successfully created.' }
        format.json { render :show, status: :created, location: @substate }
      else
        format.html { render :new }
        format.json { render json: @substate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /substates/1
  # PATCH/PUT /substates/1.json
  def update
    respond_to do |format|
      if @substate.update(substate_params)
        format.html { redirect_to @substate, notice: 'Substate was successfully updated.' }
        format.json { render :show, status: :ok, location: @substate }
      else
        format.html { render :edit }
        format.json { render json: @substate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /substates/1
  # DELETE /substates/1.json
  def destroy
    @substate.destroy
    respond_to do |format|
      format.html { redirect_to substates_url, notice: 'Substate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_substate
      @substate = Substate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def substate_params
      params.require(:substate).permit(:name, :state_id, :project_id)
    end
end

app/helpers/substates_helper.rb
module SubstatesHelper
end

app/views/substates/_form.html.erb
<%= form_for(substate) do |f| %>
  <% if substate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(substate.errors.count, "error") %> prohibited this substate from being saved:</h2>

      <ul>
      <% substate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :state_id %>
    <%= f.number_field :state_id %>
  </div>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.number_field :project_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/substates/edit.html.erb
<h1>Editing Substate</h1>

<%= render 'form', substate: @substate %>

<%= link_to 'Show', @substate %> |
<%= link_to 'Back', substates_path %>

app/views/substates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Substates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @substates.each do |substate| %>
      <tr>
        <td><%= substate.name %></td>
        <td><%= substate.state_id %></td>
        <td><%= substate.project_id %></td>
        <td><%= link_to 'Show', substate %></td>
        <td><%= link_to 'Edit', edit_substate_path(substate) %></td>
        <td><%= link_to 'Destroy', substate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Substate', new_substate_path %>

app/views/substates/new.html.erb
<h1>New Substate</h1>

<%= render 'form', substate: @substate %>

<%= link_to 'Back', substates_path %>

app/views/substates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @substate.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @substate.state_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @substate.project_id %>
</p>

<%= link_to 'Edit', edit_substate_path(@substate) %> |
<%= link_to 'Back', substates_path %>